apiVersion: apps/v1
kind: Deployment
metadata:
  name: alak-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alak-controller
  template:
    metadata:
      labels:
        app: alak-controller
    spec:
      containers:
        - name: alak-controller
          image: {{ .Values.alakController.image }}
          ports:
            - containerPort: {{ .Values.alakController.port }}
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: alak-env
                  key: REDIS_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: alak-controller
spec:
  selector:
    app: alak-controller
  ports:
    - port: {{ .Values.alakController.port }}
      targetPort: {{ .Values.alakController.port }}
